version: "3"

services:
  server:
    container_name: magebit_backend_demo
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    restart: on-failure
    volumes:
      - .:/src/app
    ports:
      - 8080:8080
    networks:
      - main-network
    command: sh -c "composer install && php migrations.php && php -S 0.0.0.0:8080"

  database:
    container_name: magebit_database_demo
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: on-failure
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - main-network

networks:
  main-network:
    driver: bridge
